server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: producer
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6000/job_queue_db}
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
